name: Build Shared Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest, windows-2019, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release library
        run: cargo build --release

      - name: List output artifacts
        run: ls -l target/release/

      - name: Upload built library
        uses: actions/upload-artifact@v3
        with:
          name: rust-shared-lib-${{ matrix.os }}
          path: target/release/
